### PR TITLE
Update homepage layout

### PR DESCRIPTION
**Pull request by vahnag**

### CODE REVIEW

**Comment by worldsoup** [comment]
@vahnag can you update this PR with syntax highlighting so that I can update code snippets more easil?

**Comment by vahnag** [comment]
yes sure, already started the work on that. will have it ready tomorrow

**Comment by worldsoup** [comment]
@vahnag can you please add link below main CTA that says 'Request A Demo' and links to this page: https://www.courier.com/request-demo

Also please use same arrow as main CTA

image

**Comment by worldsoup** [comment]
@vahnag please let me know when you update the syntax highlighting

**Comment by vahnag** [comment]
I got it working but didn't get to clean up the code yet, so will need one more day to have it ready and fix the conflicts:

https://user-images.githubusercontent.com/5208783/129278962-ef43b4a2-9b40-4c07-9e8a-5d9e3eea7dde.mov

**Comment by vahnag** [comment]
@worldsoup just pushed a commit with updated syntax highlighting and rebased with master

**Review by worldsoup — APPROVED** [review]

**Pull request merged**
